name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # amikor a main branch-re push-olsz
  workflow_dispatch:  # manuális indítás lehetősége

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - name: Node.js beállítása
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Függőségek telepítése
        run: |
          npm install --save three
          npm install --save-dev vite

      - name: Vite build
        run: npx vite build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v7
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
